theme: jekyll-theme-minimal
title: NoMoney The Don
description: Bookmark this to keep an eye on my project updates!
<html>
<head>
  <title> Bash Terminal Website</title>
  <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
  <div id="terminal">
    <div id="output"></div>
    <div id="input">
      <span id="prompt">$</span>
      <input type="text" id="command" autofocus>
    </div>
  </div>

  <script src="script.js"></script>
</body>
</html>